onboarding = false
[theme]
name = "gruvbox"
# [theme.custom]
# overlay0 = "#665c54" # inactive pane border darker

auto_switch = false
[ui]
tab_bar_position = "top"
accent = "green"
prompt_new_tab_name = false
pane_borders = "always"
pane_outer_borders = true
pane_gaps = true
window_title = "[{workspace}] {tab} - {terminal_title}"
sidebar_collapsed_mode = "hidden"
tab_bar_right = [
  { type = "command", command = "\"$HERDR_BIN_PATH\" workspace list | jq -r --arg id \"$HERDR_ACTIVE_WORKSPACE_ID\" '.result.workspaces[] | select(.workspace_id == $id) | .label'", interval_seconds = 1, timeout_seconds = 2 },
]

[ui.toast]
delivery = "herdr"

[keys]
prefix = "F12"

focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"

split_vertical = "prefix+\\"
split_horizontal = "prefix+-"
close_pane = "prefix+q"
zoom = "prefix+z"
resize_mode = "prefix+p"

new_tab = "prefix+t"
rename_tab = "prefix+r"
previous_tab = "alt+i"
next_tab = "alt+o"
switch_tab = "alt+1..9"
close_tab = "prefix+shift+q"

settings = "prefix+C"
reload_config = "prefix+R"
open_notification_target = "prefix+o"
toggle_sidebar = "prefix+s"
copy_mode = "prefix+v"

rename_workspace = ""
close_workspace = ""
detach = "prefix+d"
previous_workspace = "alt+shift+p"
next_workspace = "alt+shift+n"
previous_agent = "alt+p"
next_agent = "alt+n"

[[keys.command]]
key = "prefix+enter"
type = "shell"
command = "/home/susensio/.config/herdr/scripts/smart-split"
description = "new pane"
[[keys.command]]
key = "alt+`"
type = "popup"
command = "/home/susensio/.config/herdr/scripts/scratchpad"
description = "open scratchpad"
width = "80%"
height = "85%"
[[keys.command]]
key = "prefix+f"
type = "popup"
command = "/home/susensio/.config/herdr/scripts/sessionizer"
description = "open sessionizer"
width = "80%"
height = "80%"
[[keys.command]]
key = "prefix+g"
type = "popup"
command = "lazygit"
description = "open lazygit"
width = "80%"
height = "85%"
[[keys.command]]
key = "alt+m"
type = "popup"
command = "/home/susensio/bin/f-man"
description = "open man pages"
width = "80%"
height = "85%"

[worktrees]
directory = "~/.local/share/herdr/worktrees"

[experimental]
pane_history = true
