[tools]
biome = "latest"
"cargo:https://github.com/nushell/nufmt" = "latest"
"npm:bash-language-server" = "latest"
"npm:fish-lsp" = "latest"
ruff = { version = "latest", gen_completions = "generate-shell-completion fish" }
shellcheck = "latest"
shfmt = "latest"
taplo = { version = "latest", symlink_bins = true, gen_completions = "completions fish" }
ty = { version = "latest", gen_completions = "generate-shell-completion fish" }
