-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:LG Electronics LG HDR 4K 105NTYTFB186",
  mode = "3840x2160@60.00",
  position = "2616x-284",
  scale = 1.5,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG IPS QHD 106NTDV65794",
  mode = "2560x1440@59.95",
  position = "1536x-384",
  scale = 1.33333,
  transform = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Sharp Corporation 0x14F9",
  disabled = true,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "2", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "3", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "4", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "5", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "6", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "7", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "8", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "9", monitor = "desc:LG Electronics LG HDR 4K 105NTYTFB186" })
hl.workspace_rule({ workspace = "10", monitor = "desc:LG Electronics LG IPS QHD 106NTDV65794" })
