set-environment -ghF TMUX_CONFIG_DIR "#{d:current_file}"
set-environment -ghF TMUX_SCRIPTS_DIR "#{d:current_file}/scripts"
set-environment -ghF BIN_HOME "#{HOME}/bin"


# A -F format must be used here, not because the variable is hidden,
# but due to tmux config parses files entirely before setting the environment
# `%hidden VAR=VALUE` could not be used because `#{d:}` format
source -F "#{TMUX_CONFIG_DIR}/conf.d/*.conf"
