EDITOR=hx
SUDO_EDITOR=$HOME/.local/bin/hx
PAGER=less
LESS="--RAW-CONTROL-CHARS --incsearch --quit-if-one-screen --mouse --wheel-lines=3"
MANPAGER="bat --style=plain --language=man --strip-ansi=always"

FZF_DEFAULT_COMMAND="fd --type f --hidden --exclude=.git"
FZF_DEFAULT_OPTS_FILE="$XDG_CONFIG_HOME/fzf/opts"
