EDITOR=hx
SUDO_EDITOR=$HOME/.local/bin/hx
PAGER=less
LESS="--RAW-CONTROL-CHARS --incsearch --quit-if-one-screen --mouse --wheel-lines=3"
MANPAGER="bat --style=plain --language=man --strip-ansi=always"
