gui:
  nerdFontsVersion: 3
  scrollHeight: 10
  theme:
    selectedLineBgColor:
      - black
os:
  editPreset: 'nvim'
git:
  paging:
    colorArg: always
    pager: "delta --dark --paging=never"
promptToReturnFromSubprocess: false
notARepository: quit
