# Tmux roles are set directly from the resolved Omarchy palette.
set-environment -gh PANE_BG "{{ background }}"
set-environment -gh PANE_FG "{{ bright_foreground }}"
set-environment -gh PANE_INACTIVE_BG "{{ mix background foreground 4% }}"
set-environment -gh PANE_INACTIVE_FG "{{ foreground }}"
set-environment -gh POPUP_BG "{{ background }}"
set-environment -gh POPUP_FG "{{ bright_foreground }}"
set-environment -gh CURSOR "{{ cursor }}"
set-environment -gh BORDER_MUTED "{{ dark_foreground }}"
set-environment -gh BORDER_MODE "{{ yellow }}"
set-environment -gh BORDER_SYNC "{{ red }}"
set-environment -gh BORDER_NORMAL "{{ bright_green }}"
set-environment -gh MARK_FG "{{ background }}"
set-environment -gh STATUS_BG "{{ lighter_background }}"
set-environment -gh STATUS_FG "{{ foreground }}"
set-environment -gh STATUS_MUTED "{{ dark_foreground }}"
set-environment -gh SESSION_BG "{{ light_foreground }}"
set-environment -gh SESSION_FG "{{ background }}"
set-environment -gh NORMAL_BG "{{ selection }}"
set-environment -gh NORMAL_FG "{{ light_foreground }}"
set-environment -gh ACTIVE_BG "{{ green }}"
set-environment -gh ACTIVE_FG "{{ background }}"
set-environment -gh MODE_BG "{{ yellow }}"
set-environment -gh SELECT_BG "{{ bright_magenta }}"
set-environment -gh BADGE_FG "{{ background }}"
set-environment -gh PREFIX_BG "{{ blue }}"
set-environment -gh PREFIX_ACTIVE_BG "{{ bright_blue }}"
# Mixed toward the foreground, not the background: black text needs the lighter
# half of yellow, and a light theme darkens it the same way.
set-environment -gh MESSAGE_BG "{{ mix yellow foreground 25% }}"
set-environment -gh MESSAGE_FG "{{ background }}"
