#!/bin/sh
git_cmd="/usr/bin/git --git-dir=${YADM_HOOK_REPO} --work-tree=${YADM_HOOK_WORK}"

# Second, add possible new files
include="${XDG_CONFIG_HOME:-$HOME/.config}/yadm/include"
# If such config file exists
[ -r "$include" ] && cat "$include" |
  # environment variable substitution
  envsubst |
  # expand globs
  # https://unix.stackexchange.com/a/671797/279958
  xargs -I{} bash -O nullglob -c "echo {}" | xargs -n1 |
  # remove symlinks
  xargs -I{} find {} -type f -or -type l |
  # mark files as intent to add
  eval "$git_cmd add --intent-to-add --pathspec-from-file=-"
