#!/bin/sh
git_cmd="/usr/bin/git --git-dir=${YADM_HOOK_REPO} --work-tree=${YADM_HOOK_WORK}"

# Undo pre_commit: remove previously intent-to-added files
# or added and deleted
eval $git_cmd 'diff --name-only --diff-filter=AD -z' |
  # ignore blanks and prepend repo root folder
  awk 'BEGIN {RS="\0";OFS="\n"} NF {print "\":/" $0 "\""}' |
  # remove from index
  xargs -r $git_cmd reset -q --
