unbind -T root -a
unbind -T prefix -a

set -su command-alias

# tab = window
set -a command-alias find-tab=find-window
set -a command-alias kill-tab=kill-window
set -a command-alias last-tab=last-window
set -a command-alias link-tab=link-window
set -a command-alias list-tabs=list-windows
set -a command-alias move-tab=move-window
set -a command-alias new-tab=new-window
set -a command-alias next-tab=next-window
set -a command-alias previous-tab=previous-window
set -a command-alias rename-tab=rename-window
set -a command-alias resize-tab=resize-window
set -a command-alias respawn-tab=respawn-window
set -a command-alias rotate-tab=rotate-window
set -a command-alias select-tab=select-window
set -a command-alias set-tab-option=set-window-option
set -a command-alias show-tab-options=show-window-options
set -a command-alias split-tab=split-window
set -a command-alias swap-tab=swap-window
set -a command-alias unlink-tab=unlink-window

# reset hooks (only the ones that contain something)
run 'tmux show-hooks -g | cut -d"[" -f1 --only-delimited | uniq | xargs --no-run-if-empty -I{} tmux set-hook -gu {}'
run 'tmux show-hooks -gw | cut -d"[" -f1 --only-delimited | uniq | xargs --no-run-if-empty -I{} tmux set-hook -gwu {}'
