set -g prefix C-Space
# bind -n C-Space run -b "$HOME/Projects/tmux-clue/scripts/timer.sh prefix"
bind C-Space send-prefix

set -g default-shell "/usr/bin/fish"

set -sa terminal-features "*:hyperlinks"

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -g escape-time 10
# Timeout between repeteable keys
set -g repeat-time 700

set -g history-limit 50000
# Super useful when using "grouped sessions" and multi-monitor setup
set -g aggressive-resize on

set -g detach-on-destroy no-detached


# Expand (equalize) panes evenly, only when not previously adjusted.
# By default, and reset when only one pane
set -gw @auto_equalize 1
set-hook -ga pane-exited { if -F "#{==:#{window_panes},1}" "set -w @auto_equalize 1"}

# Equalizing fires `resize-pane` by default, this is needed for discerning resizing vs equalizing
set -aF command-alias equalize-panes="set -w @equalizing 1 ; select-layout -E ; set -uw @equalizing"
set-hook -ga after-resize-pane 'if -F "#{!:#{@equalizing}}" "set -w @auto_equalize 0"'

# Actual hooks for auto_equalization
set-hook -ga after-split-window 'if -F "#{@auto_equalize}" "equalize-panes"'
set-hook -ga pane-exited { if -F "#{&&:#{@auto_equalize},#{==:#{hook_window},#{window_id}}}" "equalize-panes" }
# The previous (pane-exited) does not work https://github.com/tmux/tmux/issues/4985 so thes remain-on-exit hack would be needed
# set -g remain-on-exit on
# set-hook -g pane-died { if -F "#{e|>:#{window_panes},1}" { kill-pane ; select-layout -E } { kill-pane } }
# set-hook -g after-kill-pane "select-layout -E"

# set-hook -g after-move-pane "select-layout -E"

# This is not perfect, but lets say that if config prints something, it is an error...
bind -N "Reload config" r run-shell ' \
  out=$(tmux source "#{TMUX_CONFIG_DIR}/tmux.conf" 2>&1); \
  if [ -z "$out" ]; then \
    tmux display "Config reloaded!"; \
  else \
    echo "$out"; \
    tmux display "Config errors detected!"; \
  fi'
