set -a command-alias last-session='switch-client -l'
set -a command-alias new-split="run '$TMUX_SCRIPTS_DIR/new-split 2>&1'"
set -a command-alias sessionizer="run '$TMUX_SCRIPTS_DIR/sessionizer 2>&1'"
set -a command-alias scratchpad="run '$TMUX_SCRIPTS_DIR/scratchpad --client #{client_tty} 2>&1'"
set -a command-alias man="run '$TMUX_SCRIPTS_DIR/scratchpad --client #{client_tty} --name man $BIN_HOME/f-man 2>&1''"
set -a command-alias lazygit="run '$TMUX_SCRIPTS_DIR/scratchpad --client #{client_tty} --name lazygit $TMUX_SCRIPTS_DIR/_lazygit 2>&1''"
