%if "#{m:*_scratchpad,#{b:socket_path}}"
    set -g status off
    set -g pane-border-status off
    set -g detach-on-destroy on
    set-hook -ga window-unlinked "detach"
    set -g remain-on-exit off
%else
    # Auto close children scratchpad
    set-hook -ga session-closed "run '$TMUX_SCRIPTS_DIR/scratchpad clean --session #{q:hook_session}'"
%endif
