[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
leftshift = overload(shift, capslock)
# space = lettermod(alt, space, 250, 100)


# FORCE Ctrl+Space to bypass the lettermod logic entirely
# control+space = macro(control+space)
# [control]
# space = macro(control+space)
