[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
leftshift = timeout(layer(shift), 1000, capslock)
rightalt = oneshot(altgr)
# space = lettermod(alt, space, 250, 100)


# FORCE Ctrl+Space to bypass the lettermod logic entirely
# control+space = macro(control+space)
# [control]
# space = macro(control+space)

[control]
# Skip the capslock-hold timeout when shift is combined with control.
leftshift = layer(shift)
