return {
   -- { -- none-ls
   --   "nvimtools/none-ls.nvim",
   --   event = "LazyFile",
   --   dependencies = {
   --     "williamboman/mason.nvim",
   --     "nvim-lua/plenary.nvim"
   --   },
   --   opts = {
   --     sources = {
   --
   --     },
   --   },
   -- },
   --
   -- { -- mason-null-ls
   --   "jay-babu/mason-null-ls.nvim",
   --   event = "LazyFile",
   --   dependencies = { "nvimtools/none-ls.nvim" },
   --   opts = {
   --     ensure_installed = nil,
   --     automatic_installation = true,
   --     -- Disable automatic , make config stateless
   --     handlers = function() end,
   --   },
   -- },
}
