#!/usr/bin/env bash
# Smart lazygit that uses yadm repo when it should
session_path=$(tmux display -p '#{session_path}')

case "$session_path" in
  $HOME/.config/* | $home/bin)
    lazygit \
      --work-tree "$HOME" \
      --git-dir "$HOME/.local/share/yadm/repo.git"
    ;;
  *) lazygit ;;
esac
