#!/usr/bin/env bash
# Fancy tree view of tmux sessions windows and panes

TMUX_SCRIPTS="$(dirname "$(realpath "$0")")"

# If not provided, current session
target_id="${1:-$(tmux display -pF '#{session_id}')}"

# Colors
RED="\e[31m"
BLUE="\e[94m"
GREEN="\e[32m"
YELLOW="\e[33m"
GRAY="\e[90m"
LGRAY="\e[37m"
BOLD="\e[1m"
ITALIC="\e[3m"
RESET="\e[0m"

# We check if the session exists
if ! tmux has-session -t "$target_id" 2>/dev/null; then
  # If it's not a session ID, it might be a name
  # But in our case, sessionizer passes session_id
  echo -e "${RED}Session $target_id not found${RESET}"
  exit 1
fi

# Fetch session info
# We use the 'ls' script if possible, or direct tmux ls
format='#{session_id}:#{session_name}:#{T:tree_mode_format}:#{session_path}'
session_info=$(tmux ls -f "#{==:#{session_id},$target_id}" -F "$format")

IFS=':' read -r s_id s_name s_info s_path <<<"$session_info"

# Print Session
echo -en "${BLUE}${BOLD}[$s_name]${RESET}"
echo -en "${BLUE}: $(echo "$s_path" | sed "s|$HOME|~|")"
echo -e "${ITALIC}${LGRAY} - $s_info${RESET}"

# Print Windows
readarray -t windows < <(tmux lsw -t"$s_id" -F '#{window_id}:#{window_index}:#{window_name}:#{window_active}')
w_id_last=$(echo "${windows[-1]}" | cut -d':' -f1)

for window in "${windows[@]}"; do
  IFS=':' read -r w_id w_i w_name w_active <<<"$window"

  # Tree structure
  echo -en "${GRAY}"
  [[ $w_id != $w_id_last ]] && echo -en "├──" || echo -en "└──"
  echo -en "${RESET}"

  # Window name
  echo -en "${YELLOW}󰓩 ${BOLD}$w_i:$w_name${RESET}"
  [[ $w_active -eq 1 ]] && echo -en "${BOLD}*"
  echo

  # Print Panes
  readarray -t panes < <(tmux lsp -t"$w_id" -F '#{pane_id}:#{pane_current_command}:#{pane_title}')
  p_id_last=$(echo "${panes[-1]}" | cut -d':' -f1)

  for pane in "${panes[@]}"; do
    IFS=':' read -r p_id p_cmd p_title <<<"$pane"

    # Tree structure
    echo -en "${GRAY}"
    [[ $w_id != $w_id_last ]] && echo -en "│  " || echo -en "   "
    [[ $p_id != $p_id_last ]] && echo -en "├──" || echo -en "└──"
    echo -en "${RESET}"

    # Pane name
    echo -en "${GREEN} ${BOLD}$p_cmd${RESET}"
    echo -e "${GREEN}: ${LGRAY}$p_title${RESET}"
  done
done
