#!/usr/bin/env bash
set -eu
[[ "${DEBUG:-}" == "1" ]] && set -x
# exec 2> /tmp/tmux-sessionizer.log

# --- Configuration ---
TMUX_SCRIPTS="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/scripts"
SEP=$'\x1f'
LOOKUP_PATHS=($HOME/Projects ${XDG_CONFIG_HOME:-$HOME/.config})

declare -A ICONS=(
  [NEW]="󰄱 "
  [TMUX]=" "
  [DIR]=" "
  [PROJECT]="󰊢 "
  [CONFIG]=" "
  [CODE]=" "
)

# --- Data Helpers ---
to_row() {
  local row=(
    "$1" # kind
    "$2" # session_id
    "$3" # session_name
    "$4" # session_path
    "$5" # fzf_display
  )
  local IFS="$SEP"
  echo "${row[*]}"
}

path_to_row() {
  local path=$1
  local short_path="${path##*/}" # vastly faster than basename

  case "$path" in
    $HOME/.config/*) kind="CONFIG" ;;
    "$HOME/bin" | $HOME/bin/*) kind="CODE" ;;
    $HOME/Projects/*) kind="PROJECT" ;;
    *) kind="DIR" ;;
  esac
  local icon=${ICONS[$kind]}

  to_row "$kind" "" "$kind $short_path" "$path" "$icon ${path/#$HOME/\~}"
}

parse_row() {
  # IFS=$SEP read -r kind session_id session_name session_pretty_name session_path fzf_display <<<"$1"
  IFS=$SEP read -r kind session_id session_name session_path fzf_display <<<"$1"
}

# --- Source Gathering ---
list_sources() {
  to_row "NEW" "" "" "$HOME" "${ICONS[NEW]} +New session"

  local session_row_format=$(to_row "SESSION" "#{session_id}" "#{session_name}" "#{session_path}" "${ICONS[TMUX]} #{?@session_pretty_name,#{@session_pretty_name},#S}")

  # 1. Sessions sorted by recent activity
  {
    sessions=$("${TMUX_SCRIPTS}/ls" --mru -F "$session_row_format" 2>/dev/null)
    if [[ -n "$sessions" ]]; then
      # Current session go last
      echo "$sessions" | tail -n +2
      echo "$sessions" | head -n 1
    fi
    # }
    {
      # 2. Zoxide MRU folders
      zoxide query --list | head -n 50

      # 3. Defined lookup dirs
      find "${LOOKUP_PATHS[@]}" -maxdepth 1 -mindepth 1 -type d 2>/dev/null

      # 4. Current directory and its subfolders
      local current_path=$(test -n "${TMUX:-}" && tmux display -pF '#{pane_current_path}' || echo "$PWD")
      echo "$current_path"
      find "$current_path" -maxdepth 1 -mindepth 1 -type d 2>/dev/null
    } | awk '!seen[$0]++' | while read -r path; do
      path_to_row "$path"
    done
  } | awk -W interactive -F"$SEP" '!seen[$3]++'
}

if [[ "${1:-}" == "--list" ]]; then
  # Print the list without `New session`, used to remove first session when something was kindd.
  list_sources | tail -n +2
  exit
fi

# Can be used without interaction
if [[ -n "${1:-}" ]]; then
  selection=$(path_to_row "$1")
else
  # Avoid nested popups
  if [[ -n "${TMUX_PARENT:-}" ]]; then
    tmux detach
    export TMUX=$TMUX_PARENT
  fi

  preview_cmd="[[ {1} == 'NEW' ]] && exit || [[ {1} == 'SESSION' ]] && ${TMUX_SCRIPTS}/preview-session {2} || eza --color=always --icons --tree --level=2 --git-ignore -- {4}"

  selection=$(
    list_sources | fzf \
      --delimiter="$SEP" \
      --with-nth=-1 \
      --no-sort \
      --scheme=path \
      --preview="$preview_cmd" \
      --bind="change:reload-sync(${TMUX_SCRIPTS}/sessionizer --list)+unbind(change)"
  )
fi

[[ -z "$selection" ]] && exit

parse_row "$selection"

case "$kind" in
  NEW)
    target_session=$(tmux new-session -d -P -F "#{session_id}")
    ;;
  SESSION)
    target_session="$session_id"
    ;;
  *)
    icon=${ICONS[$kind]}
    short_session_name=$(basename "$session_path")

    session_name="${kind} $(echo "$short_session_name" | tr '.' '_')"
    session_pretty_name="${icon}${short_session_name}"

    if tmux has-session -t "=$session_name" 2>/dev/null; then
      target_session="$(tmux list-sessions -f "#{==:#{session_name},$session_name}" -F '#{session_id}')"
    else
      target_session=$(tmux new-session -d -s "$session_name" -c "$session_path" -P -F "#{session_id}")
      tmux set-option -t "$target_session" '@session_pretty_name' "${session_pretty_name}"
      zoxide add "$session_path"
    fi
    ;;
esac

# --- Execution ---
if [[ -n "$TMUX" ]]; then
  tmux switch-client -t "$target_session"
else
  tmux attach-session -t "$target_session"
fi
