#!/usr/bin/env bash
# DOES NOT WORK WELL if script needs arguments because https://github.com/tmux/tmux/issues/4784
CURRENT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

for file in "$CURRENT_DIR/"*; do
    [[ -x "$file" ]] || continue

    name=$(basename "$file")
    tmux set -a command-alias "${name}=run '${file}'"
done
