#!/bin/bash
# TOOD: this does not work well for global scratch
# maybe I should delete global scratchs....

tmux_scripts="$XDG_CONFIG_HOME/tmux/scripts"

is_scratch="$(tmux show -vq '@is_scratch')"

# Hide scratch session, otherwise it will appear on top
if [[ -n "$is_scratch" ]]; then
  $tmux_scripts/scratch-toggle
  # save it for restore
  tmux set -t "$current_session" -q @scratch_visible true
fi

current_session="$(tmux display -pF '#{session_id}')"
current_client="$(tmux display -pF '#{client_tty}')"

rotate() {
  direction="$1"

  readarray -t sessions < <("$tmux_scripts"/ls --id --nohidden | sort -n -k1.2 )

  for i in "${!sessions[@]}"; do
    if [[ ${sessions[$i]} == "$current_session" ]]; then
      break
    fi
  done

  i=$(( i + direction ))
  i_max=$(( "${#sessions[@]}" - 1 ))

  # wrap
  [[ $i -lt 0 ]] && i=$i_max
  [[ $i -gt $i_max ]] && i=0

  tmux switch-client -c "$current_client" -t "${sessions[$i]}"
}

last() {
  last_session="$("$tmux_scripts"/mru)"
  if [[ -n "$last_session" ]]; then
    tmux switch-client -c "$current_client" -t "$last_session"
  fi
}

case "$1" in
  -n) rotate "+1" ;;
  -p) rotate "-1" ;;
  -l) last ;;
  *) echo "Unknown flag" >&2 && exit 1
esac


if tmux show '@scratch_visible' > /dev/null; then
  tmux set -u @scratch_visible
  $tmux_scripts/scratch-toggle
fi
