# This is a basic workflow to help you get started with Actions

name: CI

on: 
  - push
  - pull_request
  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch

jobs:
  fish-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1
      - uses: fish-actions/syntax-check@v1
  # fish-format:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: fish-actions/install-fish@v1
  #     - uses: fish-actions/format-check@v1
