name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  fish-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1
      - uses: extractions/setup-just@v4
      - name: Run Fish checks
        run: just --justfile .config/justfile fish-syntax

  bash-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v4
      - name: Install ShellCheck and shfmt
        run: sudo apt-get update && sudo apt-get install --yes shellcheck shfmt
      - name: Run Bash checks
        run: just --justfile .config/justfile bash-syntax shellcheck

  data-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v4
      - name: Run JSON and TOML checks
        run: just --justfile .config/justfile json-syntax toml-syntax
